### ISSUE TITLE
Display only class name instead of `path::class name`?

### ISSUE THREAD

**Issue by ckcollab** [pchomik/pytest-spec#10]
Heyo, thanks so much for putting this together! Works perfectly, but I was wondering if it was possible to turn this:

```
src/apps/businesses/tests/office_mgmt.py::OfficeManagementTests
    [PASS]  Can only add office to company you belong to
```

Into this

```
OfficeManagementTests
    [PASS]  Can only add office to company you belong to
```

Changing `some/path::ClassName` into `ClassName`? 

Not sure the best way to go about it, `py.test --spec --spec-hide-paths` seems weird.

**Comment by pchomik** [comment]
Hello,

Let's add some new parameter. I have to think about proper name.

**Comment by ckcollab** [comment]
Yeah I can't think of a good name either... could also have special formatting from `pytest.ini`? Like
```ini
[pytest]
spec_hide_paths=True
# or
spec_path = "{ path }::{ class_name }"
# And for my purposes I'd do
spec_path = "{ class_name }"
```

But, that may be overkill, unless some other functionality could benefit from such a setup?

Thanks again 💃

**Comment by pchomik** [comment]
I like spec_hide_paths.
IMO we should provide pytest.ini and command line option for that.

**Comment by 0x64746b** [comment]
I'd actually like to go one step further and also split the class name at capitalized letters and drop [the `Test` prefix](http://doc.pytest.org/en/latest/goodpractices.html#test-discovery), to get something that behaves like the [pinocchio spec plugin](http://darcs.idyll.org/~t/projects/pinocchio/doc/#spec-generate-test-description-from-test-class-method-names)/[testdox](http://agiledox.sourceforge.net/):

    Office Management
        [PASS]  Can only add office to company you belong to

How do you feel about this?

Thx
dtk
