### ISSUE TITLE
Prettier doctest names

### ISSUE THREAD

**Issue by jayvdb** [pchomik/pytest-spec#16]
For doctest, the output is like

```
dependency_management/requirements/GoRequirement.py::
    [PASS]  Dependency management.requirements.GoRequirement.GoRequirement. init
    [PASS]  Dependency management.requirements.GoRequirement.GoRequirement.install command
```

It should be something similar to

```
dependency_management/requirements/GoRequirement.py::
    [PASS]  __init__
    [PASS]  install command
```

**Comment by pchomik** [comment]
@jayvdb could you provide some kind of test file to investigate what is needed to implement this?

**Comment by pchomik** [comment]
@jayvdb could you check with the latest version?

**Comment by jayvdb** [comment]
Packaged new version https://build.opensuse.org/package/show/devel:languages:python:pytest/python-pytest-spec

Will retest doctest and report back. Thx

**Comment by pchomik** [comment]
Any update on this?
