### ISSUE TITLE
drone.io links on readme are dead

### ISSUE THREAD

**Issue by arjunsinghy96** [pchomik/pytest-spec#17]
Travis CI is used for continuous integration. Continuous integration status image link needs to be updated to travis-ci. `https://travis-ci.org/pchomik/pytest-spec.svg?branch=master`.

Link to latest plugin is also broken.

**Comment by pchomik** [comment]
Will be solved by #14 change. I have to sit and finish it.
Thanks for report.

**Comment by pchomik** [comment]
The README was fixed and packages are available in github releases and on pypi server.
