### ISSUE TITLE
Method under test should be highlighted by color not <> characters

### ISSUE THREAD

**Issue by pchomik** [pchomik/pytest-spec#2]
There is no good way to highlight method under test. Additional character don't look like clear solution. I want to try with highlighting color (yellow).

**Comment by amcgregor** [comment]
Colour based approaches would break automatic processing of the resulting report, which would strip ANSI sequences.

**Comment by pchomik** [comment]
Thanks for comment. Colors will be implemented under seperate flag.

**Comment by pchomik** [comment]
Colors are available from version 2.0.0
