### ISSUE TITLE
UserWarning: arguments declared in hookspec issued in pytest 4.2.0

### ISSUE THREAD

**Issue by bbengfort** [pchomik/pytest-spec#21]
It looks like pytest made some changes in their 4.2 release that affect pytest-spec. Namely, I'm receiving a bunch of the following warnings:

```
[snip]/site-packages/pytest_spec/patch.py:23: UserWarning: Argument(s) ('config',) which are declared in the hookspec can not be found in this hook call
    res = self.config.hook.pytest_report_teststatus(report=report)
```

I can ignore these errors, but it would be nice if we can sort them out. I'm happy to investigate and submit a PR if you'd like to point me the right direction.

**Comment by lvieirajr** [comment]
Bump, Facing the same problem.

**Comment by hbarcelos** [comment]
Same here. Any updates?

**Comment by jhermann** [comment]
This is all the fix you need. Question is whether someone is able make a release?
```diff
--- a/pytest_spec/patch.py
+++ b/pytest_spec/patch.py
@@ -20,7 +20,7 @@ def pytest_runtest_logreport(self, report):
 
     Hook changed to define SPECIFICATION like output format. This hook will overwrite also VERBOSE option.
     """
-    res = self.config.hook.pytest_report_teststatus(report=report)
+    res = self.config.hook.pytest_report_teststatus(report=report, config=self.config)
     cat, letter, word = res
     self.stats.setdefault(cat, []).append(report)
     if not letter and not word:
```

**Comment by AnneTheAgile** [comment]
yes agree how do we find out how to make a build ? 

This was also fixed on fork: https://github.com/esnowkropla/pytest-spec/commit/a879fe79ae4032fd918302288795b9a70f810c40

it would be great to fix the warning officially.
