### ISSUE TITLE
Maintainer help please pchomik

### ISSUE THREAD

**Issue by AnneTheAgile** [pchomik/pytest-spec#24]
Since there has not been a release in a long time and we have a hotfix that would be great to do, could we convince the author to come out and either make a release or share privilges ? 

Please see 
UserWarning: arguments declared in hookspec issued in pytest 4.2.0 · Issue #21 · pchomik/pytest-spec: https://github.com/pchomik/pytest-spec/issues/21

**Comment by holmesjr** [comment]
We could fork it somewhere and start maintaining it there too.

**Comment by hugovk** [comment]
@AnneTheAgile You can also email @pchomik, see setup.py for the address.

One option may be to host at https://github.com/pytest-dev.

**Comment by atvaccaro** [comment]
That's a really good idea.

**Comment by pchomik** [comment]
I will look into code at Sunday.

**Comment by pchomik** [comment]
New version 2.0.0 was released.
