### ISSUE TITLE
Different content on PyPI

### ISSUE THREAD

**Issue by frenzymadness** [pchomik/pytest-spec#31]
Hello.

The source tarball for version 3.0.4 on PyPI looks different from what you have here on GH. For example, on PyPI, there is still setup.py file.

Could you please take a look?

**Comment by pchomik** [comment]
Hello,

The content on pypi is ok. 
Please look here: https://github.com/pchomik/pytest-spec/runs/1173141000?check_suite_focus=true
The deployment was done automatically. This is a **magic** of poetry. The poetry is available in development. After building python package the pyproject.toml is translated to setup.py. From user point of view the package generated by setuptools and poetry are the same.

Is it a problem for you @frenzymadness ?

**Comment by frenzymadness** [comment]
Interesting. I did not know that, thank you. I'm maintaining this package in Fedora and a problem I have to solve now is that the latest tarball on PyPI does not contain tests so I have to switch to Github as a source and find a different way how to build this package.
