### ISSUE TITLE
Stopped working after upgrading from 2.0.0 to 3.0.x on Python 3.8

### ISSUE THREAD

**Issue by lvieirajr** [pchomik/pytest-spec#32]
Hi,
I just trying upgrading my version of pytest-spec on a project from 2.0.0 to 3.0.4 and the output of the tests just went back to the standard pytest-looking output.
Im running python 3.8

**Comment by pchomik** [comment]
Hi,

What is your executed command?
What is your pytest configuration (setup.cfg or pytest.ini files)?

**Comment by lvieirajr** [comment]
executed command is: `pytest tests/`
On setup.cfg I have this:
```
[tool:pytest]
addopts = -s -vv --spec
mock_use_standalone_module = true
python_files = test_*.py
```

**Comment by lvieirajr** [comment]
Ok, so apparently I found out what the problem is:
the `--spec` is conflicting with pytest's `-v`.

**Comment by pchomik** [comment]
Great to hear that you found where was the problem.
The plugin will not be activated for `-v` and `-q` pytest flags.
