### ISSUE TITLE
Could you please add tests/ and license to PyPI tarball?

### ISSUE THREAD

**Issue by MeggyCal** [pchomik/pytest-spec#33]
I would like to run tests during the build, but I am unable to build GitHub tarball easily. The tests/ directory once was in the PyPI tarball, why did it disappear?

Also, could you please add the license?

**Comment by jayvdb** [comment]
PyPI sdist for 3.0.5 did contain a `LICENSE.txt`.

But it should also contain tests.  Ah, using poetry.  Easy.
