### ISSUE TITLE
Conda Package Not Found

### ISSUE THREAD

**Issue by ndanielsen** [pchomik/pytest-spec#41]
Thank you for your work on this wonderful package.

I'm running into an issue when I'm installing this package via conda in CI. pytest-spec==3.0.4 is not found on conda-forge.

```
PackagesNotFoundError: The following packages are not available from current channels:

  - pytest-spec==3.0.4

Current channels:

  - https://conda.anaconda.org/conda-forge/linux-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://conda.anaconda.org/spyder-ide/linux-64
  - https://conda.anaconda.org/spyder-ide/noarch
  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch
````

I noticed that older versions were previously public on conda-forge.

https://anaconda.org/conda-forge/pytest-spec

Thanks for this package and you work on it.

**Comment by pchomik** [comment]
Hello,

I'm not sure who uploaded pytest-spec to anaconda environment. For sure not me.

Looks like process stopped when I switched from setup.py file to poetry.
Issue is related to: https://github.com/python-poetry/poetry/issues/190

Do you know how to find contact person who uploaded pytest-spec to anaconda?

**Comment by pchomik** [comment]
@ndanielsen I can share information about poetry and help to build conda logic but I don't know this environment. Would you like to contribute and add conda build/push logic to project?

**Comment by ndanielsen** [comment]
@pchomik sure, happy to help package it for conda-forge. 

I don't know who uploaded it before, I think following this guidance might allow pytest-spec to make it up on conda-forge:

https://conda-forge.org/docs/maintainer/adding_pkgs.html

**Comment by pchomik** [comment]
I successfully build pytest-spec but there is one problem. Package size increased from ~150kB to ~4MB because of poetry dependency. I'm not sure how to remove it from final package.

**Comment by pchomik** [comment]
Closing - No response from author. I'm not using conda
