### ISSUE TITLE
Add python 3.10 to pipeline

### ISSUE THREAD

**Issue by pchomik** [pchomik/pytest-spec#47]
Python 3.10 was released: https://www.python.org/downloads/release/python-3100/ and should be added to pipeline to ensure that plugin is still working.

**Comment by pchomik** [comment]
Blocked by https://github.com/python-poetry/poetry/issues/4846

**Comment by mnezh** [comment]
> Blocked by [python-poetry/poetry#4846](https://github.com/python-poetry/poetry/issues/4846)
it looks like not anymore
